---
# tasks file for roles/aws
- name: Create security group
  amazon.aws.ec2_security_group:
    name: "{{ security_group }}"
    description: "Security group for EC2 Instance"
    region: "{{ region }}"
    aws_access_key: "{{ec2_access_key}}"  
    aws_secret_key: "{{ec2_secret_key}}"  
    rules:                                 
      - proto: tcp
        ports:
          - 22
        cidr_ip: 0.0.0.0/0
        rule_desc: allow all on ssh port
      - proto: tcp
        ports:
          - 8080
        cidr_ip: 0.0.0.0/0
        rule_desc: allow all on ssh port

- name: Start an instance with a public IP address
  amazon.aws.ec2_instance:
    name: "public-compute-instance-24"
    key_name: "{{ key_name }}"
    instance_type: "{{ instance_type }}"
    security_group: "{{ security_group }}"
    aws_access_key: "{{ ec2_access_key }}"
    aws_secret_key: "{{ ec2_secret_key }}"
    region: "{{ region }}"
    user_data: "{{ lookup('file', 'docker.sh') }}"
    network:
      assign_public_ip: true
    image_id: "{{ image }}"
    tags:
      Environment: Testing1

- name: Get instances facts
  ec2_instance_info:
    aws_access_key: "{{ ec2_access_key }}"
    aws_secret_key: "{{ ec2_secret_key }}"
    region: "{{ region }}"
  register: result

# - name: Instances ID
#   debug:
#     msg: "ID: {{ item.instance_id }} - State: {{ item.state.name }} - Public DNS: {{ item.public_dns_name }}"
#   loop: "{{ result.instances }}"