- name: Initial setup of the instance
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  loop: 
    - aptitude
    - apt-transport-https
    - ca-certificates
    - curl
    - software-properties-common
    - python3-pip
    - virtualenv
    - python3-setuptools 
- name: Create directory for Docker's GPG key
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'   
- name: Add Docker GPG key
  apt_key:
    url: https://download.docker.com/{{ OS }}/{{ EXT }}/gpg
    state: present   
- name: Add Docker repository
  apt_repository:
    repo: deb https://download.docker.com/{ OS }}/{{ EXT }}/{{ ansible_lsb.codename }} stable
    state: presen
- name: Install docker-ce
  apt:
    name: docker-ce
    state: latest
    update_cache: tru
- name: Install docker
  package:
    name: docker-ce
    state: present 
- name: Add Docker group
  group:
    name: "{{ group }}"
    state: presen
- name: Add Docker user
  user:
    name: "{{ user }}"
    groups: "{{ group }}"
    append: tru
- name: Enable and start Docker services
  systemd:
    name: docker.service
    enabled: true
    state: start